version: 2

sources:
  - name: mysql_rds_sakila
    database: sakila_raw
    tables:
      - name: actor
      - name: address
      - name: store
      - name: staff
      - name: customer
      - name: country
      - name: city
      - name: rental
      - name: film
      - name: dim_date
      - name: dim_timeofday
    
